using UnityEngine;
using System.Collections.Generic;

/// <summary>
/// Manages the tech tree: research points, completing nodes, unlocking tech.
/// Science points are generated by colonists working at research stations.
/// </summary>
public class ResearchManager : MonoBehaviour
{
    [Header("Science")]
    public float sciencePoints;
    public float sciencePerSecond = 0.5f; // base rate per colonist researching

    [Header("Tree")]
    public ResearchNode[] allResearch;

    [Header("Active Research")]
    public ResearchNode currentResearch;
    public float progress;

    [Header("Unlocks")]
    public List<string> completedIds = new List<string>();

    private DayCycle _dayCycle;
    private ColonistSpawner _colonistSpawner;

    void Awake()
    {
        _dayCycle = FindObjectOfType<DayCycle>();
        _colonistSpawner = FindObjectOfType<ColonistSpawner>();

        if (allResearch == null || allResearch.Length == 0)
            InitializeDefaultResearch();
    }

    void Update()
    {
        if (_dayCycle != null && _dayCycle.IsPaused) return;

        // Generate science from colonists doing research
        float dt = Time.deltaTime * (_dayCycle != null ? _dayCycle.gameSpeed : 1f);
        float generation = 0f;

        if (_colonistSpawner != null)
        {
            foreach (Colonist c in _colonistSpawner.Colonists)
            {
                if (c != null && c.currentState == ColonistState.Working)
                {
                    // Check if colonist has a research task
                    ColonistAI ai = c.GetComponent<ColonistAI>();
                    if (ai != null && ai.currentTask == ColonistTask.Research)
                    {
                        float skillBonus = 1f + c.intellectualSkill * 0.1f;
                        generation += sciencePerSecond * skillBonus * dt;
                    }
                }
            }
        }

        sciencePoints += generation;

        // Apply to current research
        if (currentResearch != null && !currentResearch.isCompleted)
        {
            float rp = sciencePerSecond * dt; // consume science points
            if (sciencePoints > 0f)
            {
                float applied = Mathf.Min(rp, sciencePoints);
                sciencePoints -= applied;
                currentResearch.progress += applied;

                if (currentResearch.progress >= currentResearch.scienceCost)
                    CompleteResearch(currentResearch);
            }
        }

        // Auto-advance to next available
        if (currentResearch == null || currentResearch.isCompleted)
        {
            currentResearch = FindNextAvailable();
        }
    }

    /// <summary>
    /// Completes a research node and unlocks its benefits.
    /// </summary>
    void CompleteResearch(ResearchNode node)
    {
        node.isCompleted = true;
        completedIds.Add(node.id);
        Debug.Log($"[Research] Completed: {node.name}!");
        currentResearch = null;
    }

    /// <summary>
    /// Finds the next available research node based on prerequisites.
    /// </summary>
    ResearchNode FindNextAvailable()
    {
        foreach (ResearchNode node in allResearch)
        {
            if (node.isCompleted || !node.isAvailable) continue;

            // Check prerequisites
            bool preReqsMet = node.prerequisiteIds == null || node.prerequisiteIds.Length == 0;
            if (!preReqsMet)
            {
                preReqsMet = true;
                foreach (string preId in node.prerequisiteIds)
                {
                    if (!completedIds.Contains(preId)) { preReqsMet = false; break; }
                }
            }

            if (preReqsMet) return node;
        }
        return null;
    }

    /// <summary>
    /// Checks if a research is completed by ID.
    /// </summary>
    public bool IsResearched(string id) => completedIds.Contains(id);

    /// <summary>
    /// Creates default research tree if none assigned.
    /// </summary>
    void InitializeDefaultResearch()
    {
        allResearch = new ResearchNode[]
        {
            // Era 1
            new ResearchNode { id = "basic_building", name = "Базовое строительство", description = "Стены (дерево), пол, крыша", era = 1, scienceCost = 100 },
            new ResearchNode { id = "furniture", name = "Мебель", description = "Кровать, стол, стул", era = 1, scienceCost = 100, prerequisiteIds = new[]{"basic_building"} },
            new ResearchNode { id = "stoneworking", name = "Обработка камня", description = "Каменные стены, каменотёс", era = 1, scienceCost = 150 },
            new ResearchNode { id = "cooking1", name = "Кулинария I", description = "Костёр, простая еда", era = 1, scienceCost = 80 },
            new ResearchNode { id = "farming1", name = "Фермерство I", description = "Посадка базовых культур", era = 1, scienceCost = 120 },
            new ResearchNode { id = "defense1", name = "Оборона I", description = "Частокол, ловушки", era = 1, scienceCost = 120 },
            // Era 2
            new ResearchNode { id = "masonry", name = "Каменная кладка", description = "Укреплённые стены, колонны", era = 2, scienceCost = 200, prerequisiteIds = new[]{"stoneworking"} },
            new ResearchNode { id = "brewing", name = "Пивоварение", description = "Пивоварня, эль, вино", era = 2, scienceCost = 180, prerequisiteIds = new[]{"farming1"} },
            new ResearchNode { id = "metal1", name = "Металлы I", description = "Плавильня, медь", era = 2, scienceCost = 250, prerequisiteIds = new[]{"stoneworking"} },
            new ResearchNode { id = "medicine1", name = "Медицина I", description = "Травы, перевязка, госпиталь", era = 2, scienceCost = 200 },
        };

        // Make Era 1 available
        foreach (ResearchNode node in allResearch)
        {
            if (node.era == 1) node.isAvailable = true;
            if (node.prerequisiteIds == null) node.prerequisiteIds = new string[0];
        }
    }
}
